### ISSUE TITLE
Use 'default' section when 'appsec' section is missing

### ISSUE THREAD

**Issue by hokamoto** [akamai/cli-appsec#5]
Many of known API clients use 'default' section in ~/.edgerc, but Akamai CLI for Application Security reads only 'appsec' section and does not read 'default' section. This behavior puzzled me and it took time to find out the design in README. I request the command to read 'default' section when 'appsec' section is missing.

**Comment by cappellem** [comment]
I sware to god this needs to documented somewhere please! we just burnt 45 minutes messing around with this, each! and then went to log it as a bug and its the only one currently raised 💯 

Please make this very clear and centralise documentation

**Comment by cdrew12** [comment]
.edgerc parsing should surely have the same behaviour as auth module.
"$akamai auth verify" works as expected. Why doesn't appsec?

**Comment by arulned** [comment]
This is fixed. Thanks for all your inputs.
